[![class](https://img.youtube.com/vi/whtNpVWYLIo/3.jpg)](https://www.youtube.com/watch?v=whtNpVWYLIo&list=PLBHVuYlKEkUKnfbWvRCrwSuSeYh_QUlRl&index=16)
Video

In [4]:
import numpy as np

In [2]:
test_a=np.array([[1,2,3],[4,5,6]],float)

In [3]:
test_a+test_a

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [4]:
test_a-test_a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
test_a*test_a

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [6]:
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)

In [7]:
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

In [10]:
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [11]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [17]:
test_matrix = np.array(np.arange(1,7).reshape(2,-1),float)
scalar = 3
test_matrix

array([[1., 2., 3.],
       [4., 5., 6.]])

In [18]:
test_matrix + scalar

array([[4., 5., 6.],
       [7., 8., 9.]])

In [19]:
test_matrix * scalar

array([[ 3.,  6.,  9.],
       [12., 15., 18.]])

In [21]:
np.array([[1,2,3],[1,2,3],[1,2,3],[1,2,3]]) + np.array([0,1,2])

array([[1, 3, 5],
       [1, 3, 5],
       [1, 3, 5],
       [1, 3, 5]])

In [1]:
def sclar_vector_product(scalar, vector):
    result = []
    for value in vector:
        result.append(scalar * value)
    return result
iternation_max = 100000000

vector = list(range(iternation_max))
scalar = 2

In [3]:
%timeit sclar_vector_product(scalar, vector)#for loop performance

17.2 s ± 6.51 s per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [2]:
%timeit [scalar * value for value in range(iternation_max)] #list performance

5.95 s ± 586 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
%timeit np.arange(iternation_max) * scalar #numpy performance

162 ms ± 5.57 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
