[![class](https://img.youtube.com/vi/A2BT1sWKaUE/3.jpg)](https://www.youtube.com/watch?v=A2BT1sWKaUE&list=PLBHVuYlKEkUKnfbWvRCrwSuSeYh_QUlRl&index=18)
Video

In [1]:
import numpy as np

In [2]:
test_array = np.array([1,4,0,2,3,8,9,7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [3]:
test_array[test_array > 3]

array([4., 8., 9., 7.])

In [4]:
condition = test_array < 3
test_array[condition]

array([1., 0., 2.])

In [19]:
A = np.random.randint(9, 19, 135).reshape(-1, 9)
A

array([[15, 13, 17, 13, 16, 18, 11, 15, 16],
       [17, 15, 12, 13, 18, 15, 10,  9, 16],
       [11, 18, 17, 10, 15, 15, 10, 11, 15],
       [15,  9, 12, 14, 17, 13, 15, 14, 10],
       [14, 11, 14, 11, 15,  9, 13, 11,  9],
       [10, 17, 18, 18, 15, 12, 10, 10, 16],
       [18, 16, 11, 11, 12, 13, 18, 12, 10],
       [17,  9, 18, 17, 14, 11, 10, 10, 13],
       [10, 12, 10, 14, 11, 13, 15, 11, 15],
       [17, 10,  9, 15, 16, 17, 11, 18, 16],
       [12, 18, 18,  9,  9, 10, 17, 17, 12],
       [18, 13, 10, 18, 18, 17, 12, 10, 16],
       [11, 14, 15, 13, 17, 14, 10, 18, 16],
       [ 9, 16, 14, 15, 13, 12, 13, 12, 13],
       [13,  9, 11, 14, 10, 13, 10, 15, 13]])

In [20]:
B = A < 15
B.astype(np.int) #bool => int

array([[0, 1, 0, 1, 0, 0, 1, 0, 0],
       [0, 0, 1, 1, 0, 0, 1, 1, 0],
       [1, 0, 0, 1, 0, 0, 1, 1, 0],
       [0, 1, 1, 1, 0, 1, 0, 1, 1],
       [1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1, 1, 1, 0],
       [0, 0, 1, 1, 1, 1, 0, 1, 1],
       [0, 1, 0, 0, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 0, 1, 0],
       [0, 1, 1, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 1, 1, 1, 0, 0, 1],
       [0, 1, 1, 0, 0, 0, 1, 1, 0],
       [1, 1, 0, 1, 0, 1, 1, 0, 0],
       [1, 0, 1, 0, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 1]])

In [24]:
# fancy index

a = np.array([2,4,6,8],float)
b = np.array([0,0,1,3,2,1],int)
a[b]

array([2., 2., 4., 8., 6., 4.])

In [25]:
a.take(b) #recommended because of readable

array([2., 2., 4., 8., 6., 4.])

In [27]:
a = np.array([[1,4],[9,16]], float)
b = np.array([0,0,1,1,0], int)  #index must be int and non out of range
c = np.array([0,1,1,1,1], int)
a[b,c]

array([ 1.,  4., 16., 16.,  4.])

In [28]:
a[b]

array([[ 1.,  4.],
       [ 1.,  4.],
       [ 9., 16.],
       [ 9., 16.],
       [ 1.,  4.]])