In [4]:
import numpy as np

In [5]:
weight_vector = np.array([[1], [1], [1]])
x_vector = np.array([[3],[4],[5]])

In [6]:
weight_vector.T.dot(x_vector)

array([[12]])

In [7]:
import pandas as pd

In [8]:
data_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data'
df_data = pd.read_csv(data_url, sep='\s+', header = None)
df_data.columns = ['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT','MEDV']
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [9]:
df_data.values[0]

array([6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
       6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
       4.980e+00, 2.400e+01])

In [10]:
df_data['weight_0'] = 1
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  weight_0  
0     15.3  396.90   4.98  24.0         1  
1     17.8  396.90   9.14  21.6         1  
2     17.8  392.83   4.03  34.7         1  
3     18.7  394.63   2.94  33.4         1  
4     18.7  396.90   5.33  36.2         1

In [11]:
df_data=df_data.drop('MEDV',axis=1)
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  weight_0  
0     15.3  396.90   4.98         1  
1     17.8  396.90   9.14         1  
2     17.8  392.83   4.03         1  
3     18.7  394.63   2.94         1  
4     18.7  396.90   5.33         1

In [12]:
df_data.as_matrix()

/home/lee/miniconda3/envs/tensorflow/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 3.9690e+02, 4.9800e+00,
        1.0000e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 3.9690e+02, 9.1400e+00,
        1.0000e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 3.9283e+02, 4.0300e+00,
        1.0000e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 5.6400e+00,
        1.0000e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 3.9345e+02, 6.4800e+00,
        1.0000e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 7.8800e+00,
        1.0000e+00]])

In [13]:
df_data.shape # (row, column)

(506, 14)

In [14]:
df_matrix = df_data.as_matrix()
weight_vector = np.random.random_sample((14,1))

/home/lee/miniconda3/envs/tensorflow/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [16]:
df_matrix.dot(weight_vector)

array([[443.67931777],
       [399.60444069],
       [386.2468384 ],
       [362.02015238],
       [368.49905716],
       [369.59032277],
       [466.03606819],
       [485.83834169],
       [494.10709499],
       [477.33541946],
       [485.39426529],
       [475.05833217],
       [454.80977608],
       [457.14970254],
       [464.60002291],
       [454.39727248],
       [438.57666198],
       [468.75271132],
       [419.86034736],
       [460.98284629],
       [478.9415304 ],
       [472.83022829],
       [479.58434663],
       [483.53623313],
       [477.81063007],
       [450.59459798],
       [470.42115754],
       [453.59338776],
       [473.48102151],
       [467.62885117],
       [474.43017235],
       [473.60258988],
       [440.10961018],
       [470.56348642],
       [444.83403712],
       [431.9710242 ],
       [425.3329486 ],
       [419.5182495 ],
       [414.65531024],
       [404.94198163],
       [400.30269276],
       [351.25051439],
       [353.15429309],
       [357