[![class](https://img.youtube.com/vi/H6wx5PEkwoA/3.jpg)](https://www.youtube.com/watch?v=H6wx5PEkwoA&list=PLBHVuYlKEkUKnfbWvRCrwSuSeYh_QUlRl&index=15)
Video

In [1]:
import numpy as np

In [4]:
test_array=np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
test_array.sum(axis=1)

array([10, 26, 42])

In [6]:
test_array.sum(axis=0)

array([15, 18, 21, 24])

In [16]:
third_order_tensor=np.array([test_array,test_array,test_array,test_array,test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [17]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [18]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [19]:
third_order_tensor.sum(axis=0)

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60]])

In [21]:
test_array=np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
test_array.mean(), test_array.mean(axis=0)

(6.5, array([5., 6., 7., 8.]))

In [24]:
test_array.std(), test_array.std(axis=1)

(3.452052529534663, array([1.11803399, 1.11803399, 1.11803399]))

In [25]:
np.sqrt(test_array)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [28]:
np.exp(test_array)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [32]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])
np.hstack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [36]:
a = np.array([[1,2,3]])
b = np.array([[2,3,4]])
np.concatenate((a,b),axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [37]:
np.concatenate((a,b),axis=1)

array([[1, 2, 3, 2, 3, 4]])

In [39]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])